### ISSUE TITLE
Failed to init repository to store messages on SQL Server 2008 R2

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#53]
```
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'INDEX'. If this is intended as a part of a table hint, A WITH keyword and parenthesis are now required. See SQL Server Books Online for proper syntax.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Saritasa.Tools.Messages.Common.Repositories.AdoNetMessageRepository.Init(CancellationToken cancellationToken)
   at Saritasa.Tools.Messages.Common.Repositories.AdoNetMessageRepository.<AddAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Saritasa.Tools.Messages.Common.PipelineMiddlewares.RepositoryMiddleware.<HandleAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Saritasa.Tools.Messages.Common.MessagePipeline.<InternalInvokeProcessAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Saritasa.Tools.Messages.Abstractions.MessagePipelineServiceExtensions.<HandleCommandAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://github.com/Saritasa/SaritasaTools/blob/develop/src/Saritasa.Tools.Messages/Common/Repositories/QueryProviders/SqlServerQueryProvider.cs

**Comment by krasninja** [comment]
What SQL Server version are you on?

**Comment by dermeister0** [comment]
Microsoft SQL Server 2008 R2 (SP1) - 10.50.2550.0 (X64)
Compatibility level: 100
