### ISSUE TITLE
FlowUtils.Memoize is not thread-safe

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/SaritasaTools#61]
```
InvalidOperationException
Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Saritasa.Tools.Common.Utils.FlowUtils.<>c__DisplayClass12_0`2.<Memoize>b__1(TKey key)
```

**Comment by krasninja** [comment]
Fixed in 2.0.0
